#!/usr/bin/env bash
# 404 error
sudo apt-get update -y
sudo apt-get install nginx -y

# Create index.html
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Create 404.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

# Create Nginx configuration file
echo "server {
   listen 80 default_server;
   listen [::]:80 default_server;
   
   root /var/www/html;
   index index.html;

   location /redirect_me {
      return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
   }

   error_page 404 /404.html;
   location = /404.html {
      internal;
   }
}" | sudo tee /etc/nginx/sites-available/default > /dev/null

# Restart Nginx
sudo service nginx restart
