#!/usr/bin/env bash
# Installs and sets up HAProxy
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get -y update
apt-get -y install haproxy=2.0.\*
echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 265422-web-01 100.26.168.53:80 check\n\tserver 265422-web-02 54.237.111.41:80 check" > /etc/haproxy/haproxy.cfg
service haproxy restart
