#!/usr/bin/env bash
# install and configure HAProxy

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get install -y haproxy=1.8.\*

echo "ENABLED=1" >> /etc/default/haproxy

# Configure HAproxy so that it send traffic to web-01 and web-02

echo "
	listen load_balancer
	bind *:80
	balance roundrobin
	option httpclose
	option forwardfor
	server 265422-web-01 100.26.168.53 check
	server 265422-web-02 54.237.111.41 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
