#!/usr/bin/env bash
# Bash script that displays "To infinity and beyond" indefinitely with a sleep of 2 seconds in between each iteration, and prints "I am invincible!!!" when receiving a SIGTERM signal:
while true
do
echo "To infinity and beyond"
sleep 2
trap 'echo "I am invincible!!!"' SIGTERM
done
